[package]
name = "pebblevault_plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
PebbleVault = "0.6.1"
async-trait = "0.1.83"
horizon-plugin-api = "0.1.7"
horizon_data_types = "0.3.0"
horizon_logger = "0.1.0"
once_cell = "1.20.2"
serde = "1.0.214"
uuid = "1.11.0"
